// <auto-generated />
namespace PTLChi.BTL._226.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class T4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(T4));
        
        string IMigrationMetadata.Id
        {
            get { return "202205211647379_T4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
